### ISSUE TITLE
Display error after ‘resize’ event.

### ISSUE THREAD

**Issue by lwpassvoice** [gaoryrt/number-flip#13]
* in English, so that might help more people
* make sure it's not another duplicated issue

**1. steps to reproduce or any minimal reproducible example**
If there's a 'resize' after flip, it will display error. Like that:
![image](https://user-images.githubusercontent.com/22510735/56274243-fe0b7900-6130-11e9-930d-d28ab76ed054.png)
And how to reset my flip?
**2. what is expected and what is actually happening**

**Comment by gaoryrt** [comment]
fixed on https://github.com/gaoryrt/number-flip/commit/5064b9a090584af941bb17d1552a1299b590635c

**Comment by gaoryrt** [comment]
Just found it still happens before the first flip.

**Comment by gaoryrt** [comment]
fixed on https://github.com/gaoryrt/number-flip/commit/8acb4212a477f4424a73b7f93f38c31d67c1bde1
