### ISSUE TITLE
support float

### ISSUE THREAD

**Issue by whu12yz** [gaoryrt/number-flip#17]
**2. Describe the solution you'd like**
from float to float ignore decimal point, put it where it is .

**Comment by gaoryrt** [comment]
Sorry but I don’t understand what you saying 'from float to float ignore decimal point’.
Could you please describe what you encountered or make a minimal working example, like, in codesandbox.io?

**Comment by whu12yz** [comment]
I mean this repo may support flip from float to float, such as from 18.50 to 99.80.
Although, we can init two instances.
like this:
```javascript
new Flip({from: 18, to: 99})
new Flip({from:50, to: 80})
```

**Comment by gaoryrt** [comment]
you can do it by using `separator` and `seperateOnly`

i wrote a demo: https://codesandbox.io/s/compassionate-dhawan-1d3kz
