### ISSUE TITLE
UMD

### ISSUE THREAD

**Issue by jcubic** [gaoryrt/number-flip#2]
It would be nice you could use the library from CDN like https://unpkg.com/number-flip@1.0.10/flip.js it notain require from node module and exports.

It would be nice if you don't need to use bundler yourself to just test your library, it will not work in codepen.

**Comment by gaoryrt** [comment]
added on https://github.com/gaoryrt/number-flip/commit/b944b0887e599ee993dbad31f7703b506f8aa108, and demo link is added in Readme.

**Comment by jcubic** [comment]
Awesome, thanks.
