### ISSUE TITLE
Could you please publish your new update 'remove log' to npmjs.com?

### ISSUE THREAD

**Issue by brookguo** [gaoryrt/number-flip#20]
* in English, so that might help more people
* make sure it's not another duplicated issue
It's a fantastic plugin, Thank you for your share!
**1. Is your feature request related to a problem? Please describe.**
what the problem is. Ex. I'm always frustrated when [...]

**2. Describe the solution you'd like**
what you want to happen.

**3. Describe alternatives you've considered**
any alternative solutions or features you've considered.

**Comment by gaoryrt** [comment]
Done

**Comment by brookguo** [comment]
@gaoryrt Thank you very much!
