### ISSUE TITLE
About decimal use and seperateOnly

### ISSUE THREAD

**Issue by G-0404** [gaoryrt/number-flip#32]
There is no way to involve decimals when using them, I expect to use unique punctuation and multiply the original decimal by 100, but seperateOnly is not available

**Comment by G-0404** [comment]
Maybe I misunderstood? I expect you to use "separateOnly" as a punctuation point. For example, set "separateOnly:1" and the correct answer for passing in 6321 is 632.1, but in fact the answer is 6321(I set separator to '.')

**Comment by gaoryrt** [comment]
@G-0404 Just made this sandbox. It may help: https://codesandbox.io/p/sandbox/k9jlgr

**Comment by G-0404** [comment]
First of all, thank you for your answer and the case. I finally understand,
The Settings in the case you gave me are separateOnly ,But github and above npm are seperateOnly
sep**e**rateOnly  ->  sep**a**rateOnly

**Comment by gaoryrt** [comment]
So blame it on the typo, issue closed.
