### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by GizmoGrem** [gaoryrt/number-flip#6]
Library dist contains es6 features =(

**Comment by gaoryrt** [comment]
@GizmoGrem 
sorry but i have no such device to test
any error message?

**Comment by gaoryrt** [comment]
fixed in https://github.com/gaoryrt/number-flip/commit/2e73a004836f1da6bb38109bca22439b9742bc7f

**Comment by gaoryrt** [comment]
turn out it's `Array(n).keys()` that IE11 doesn't support
browserstack really helps me a lot

**Comment by Robot-L** [comment]
hello, can you fix the branch-"maxLenNum" at the same question in IE11 ,`Array(n).keys()`

**Comment by gaoryrt** [comment]
@Robot-L merged, build your own number-flip with https://github.com/gaoryrt/number-flip/tree/maxLenNum
