### ISSUE TITLE
uglifyJs can not minify the bundle when using number-flip

### ISSUE THREAD

**Issue by shengzihao** [gaoryrt/number-flip#8]
when I build my project, it shows:
Failed to minify the bundle. Error: 0.afde46cb.async.js from UglifyJs.
Then I went to check the 0.afde46cb.async.js and found that there is a 'const' in code. Unfortunately the it is from number-flip. Since UglifyJs is not supported es6, hope it may draw your attention. Thx.

**Comment by gaoryrt** [comment]
thank you.
fixed in https://github.com/gaoryrt/number-flip/commit/e0f8ccfbd9e3bfbe5ea3ff45b0b78452afde4d08

**Comment by shengzihao** [comment]
Ok, it works. Thx a lot!
