### ISSUE TITLE
超过6位数不能显示正常

### ISSUE THREAD

**Issue by seajean** [gaoryrt/number-flip#9]
比如5位数滚动到8位数

**Comment by gaoryrt** [comment]
try [branch `maxLenNum`](https://github.com/gaoryrt/number-flip/tree/maxLenNum#parameter):
`yarn add https://github.com/gaoryrt/number-flip.git\#maxLenNum`

specific the `maxLenNum` in option:
```js
new Flip({
  node: $('.app'),
  from: 100,
  to: 10000,
  maxLenNum: 5
})
```

**Comment by gaoryrt** [comment]
> `maxLenNum` `optional`: A number representing the number of digits, if not specified, length of digits would fits the [maxLenNum](https://github.com/gaoryrt/number-flip/blob/9d0e554155339502316121318bde7bf5ae57df5d/number-flip.js#L3) of given `from` and `to`. Otherwise, length of digits won't change (see more at [this issue](https://github.com/gaoryrt/number-flip/issues/5)).

**Comment by tylerrrkd** [comment]
@gaoryrt Hi, friend. It seems that the property `maxLenNum`  doesn't work. And also could not be found in doc `README.md`
https://codepen.io/Tylerrrkd/pen/aRXNNd

**Comment by gaoryrt** [comment]
@tylerrrkd it's in [branch maxLenNum](https://github.com/gaoryrt/number-flip/tree/maxLenNum#parameter), instead of master.

**Comment by gaoryrt** [comment]
> try [branch `maxLenNum`](https://github.com/gaoryrt/number-flip/tree/maxLenNum#parameter):
> `yarn add https://github.com/gaoryrt/number-flip.git\#maxLenNum`

read plz

**Comment by tylerrrkd** [comment]
@gaoryrt ooouch, did'n merge.. sorry

**Comment by gaoryrt** [comment]
> @gaoryrt 5 to 8 works now, but 8 to 5 still go wrong.

Define 'wrong'.

**Comment by Robot-L** [comment]
How to download the '.min.js' of this branch  like [https://unpkg.com/number-flip@1.0.28/dist/number-flip.min.js](https://unpkg.com/number-flip@1.0.28/dist/number-flip.min.js)?

**Comment by gaoryrt** [comment]
@Robot-L seems unpkg is unavailable to do that, but you can folk and build one for your own usage. Considering the maxLenNum branch is far behind the master branch, merge it before building is recommended.
